package org.mk96.extensible.api.crud.infrastructure.jpa.adapter.save.insert.one;

import org.mk96.extensible.api.crud.domain.port.save.insert.one.MkInsertOnePort;
import org.mk96.extensible.api.crud.infrastructure.dto.data.MkEntity;
import org.mk96.extensible.api.crud.infrastructure.jpa.repository.MkJpaRepository;
import org.mk96.extensible.api.crud.infrastructure.jpa.util.MkJpaFilterUtils;
import org.mk96.extensible.api.crud.infrastructure.mapper.MkCrudMapper;
import org.mk96.extensible.api.crud.type.exception.MkCrudException;
import org.mk96.extensible.api.crud.type.filter.MkFilter;
import org.mk96.extensible.api.crud.type.filter.exception.MkFilterNullException;
import org.mk96.extensible.api.crud.type.save.safe.insert.MkInsertSave;
import org.mk96.extensible.api.domain.model.MkDomain;
import org.mk96.extensible.api.infrastructure.adapter.AbstractMkAdapter;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.jpa.domain.Specification;

import jakarta.transaction.Transactional;
import lombok.AccessLevel;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;

@NoArgsConstructor(access = AccessLevel.PROTECTED)
@AllArgsConstructor(access = AccessLevel.PUBLIC)
public class MkJpaInsertOneAdapter<DOM extends MkDomain, EN extends MkEntity, ID>
    extends AbstractMkAdapter<DOM>
	implements MkInsertOnePort<DOM> {

	@Autowired(required = false)
	private MkJpaRepository<EN, ID> repository;

	@Autowired(required = false)
	private MkCrudMapper<DOM, EN> mapper;

	@Override
	@Transactional
	public DOM insertOne(MkInsertSave<DOM> dominsert) {

	    MkFilter<EN> enFilter = dominsert.getFilter().map(mapper::map);
	    
	    try {
	    	Specification<EN> enSpec = MkJpaFilterUtils.buildSpec(enFilter);
	    	if(repository.exists(enSpec)) {
	    		throw new MkCrudException("[insert] entity already exists");
	    	};
	    } catch (MkFilterNullException filterNullEx) {
	    	if(!filterNullEx.isAutogeneratedId()) {
	    		throw filterNullEx;
	    	}
		}

		EN enToInsert = mapper.map(dominsert.getSave());
		EN enInserted = repository.save(enToInsert);
		return mapper.map(enInserted);
	}

}
